package com.accounting.database.account

enum class AccountCategoryGroup(val type: AccountType) {
    CASH_AND_SECURITIES(AccountType.ASSET),
    INVENTORIES(AccountType.ASSET),
    OTHER_SHORT_TERM_RECEIVABLES(AccountType.ASSET),
    INVESTMENTS(AccountType.ASSET),
    MOVABLE_TANGIBLE_ASSETS(AccountType.ASSET),
    IMMOVABLE_TANGIBLE_ASSETS(AccountType.ASSET),
    FINANCIAL_ASSETS(AccountType.ASSET),
    INTANGIBLE_ASSETS(AccountType.ASSET),

    SHORT_TERM_INTEREST_BEARING_LIABILITIES(AccountType.LIABILITY),
    SHORT_TERM_PROVISIONS(AccountType.LIABILITY),
    OTHER_SHORT_TERM_LIABILITIES(AccountType.LIABILITY),
    LONG_TERM_INTEREST_BEARING_LIABILITIES(AccountType.LIABILITY),
    LONG_TERM_PROVISIONS(AccountType.LIABILITY),
    OTHER_LONG_TERM_LIABILITIES(AccountType.LIABILITY),
    SHARE_SHAREHOLDERS_OR_FOUNDATION_CAPITAL(AccountType.LIABILITY),
    RESERVES_NET_INCOME_NET_LOSS(AccountType.LIABILITY),

    REVENUE(AccountType.REVENUE),
    FINANCIAL_RESULT_REVENUE(AccountType.REVENUE),
    OTHER_REVENUE(AccountType.REVENUE),

    PRODUCTION_AND_SERVICES(AccountType.EXPENSE),
    PERSONNEL(AccountType.EXPENSE),
    TRANSPORT_LEASING_AND_MAINTENANCE(AccountType.EXPENSE),
    OPERATING_COSTS(AccountType.EXPENSE),
    FINANCIAL_RESULT_EXPENSE(AccountType.EXPENSE),
    OTHER_EXPENSE(AccountType.EXPENSE),
}