import type {Metadata} from "next";
import {Montserrat_Alternates, Hind_Madurai} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const montserratAlternates = Montserrat_Alternates({
    variable: "--font-montserrat-alternates",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

const hindMadurai = Hind_Madurai({
    variable: "--font-hind-madurai",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${montserratAlternates.variable} ${hindMadurai.variable} antialiased`}>
        <Header/>
        <div className={`mx-auto container`}>
            {children}
        </div>
        </body>
        </html>
    );
}