package database.account

enum class AccountCategory(
    val group: AccountCategoryGroup,
) {
    CASH(AccountCategoryGroup.CASH_AND_SECURITIES),
    BANK_ACCOUNT(AccountCategoryGroup.CASH_AND_SECURITIES),
    SHORT_TERM_SECURITIES(AccountCategoryGroup.CASH_AND_SECURITIES),

    MERCHANDISE(AccountCategoryGroup.INVENTORIES),
    RAW_MATERIALS(AccountCategoryGroup.INVENTORIES),
    MATERIALS(AccountCategoryGroup.INVENTORIES),
    SUPPLIES_AND_CONSUMABLES(AccountCategoryGroup.INVENTORIES),
    MERCHANDISE_ON_CONSIGNMENT(AccountCategoryGroup.INVENTORIES),
    FINISHED_PRODUCT(AccountCategoryGroup.INVENTORIES),
    UNFINISHED_PRODUCT(AccountCategoryGroup.INVENTORIES),

    ADVANCES_AND_LOANS_TO_OTHERS(AccountCategoryGroup.OTHER_SHORT_TERM_RECEIVABLES),
    RECEIVABLES_FROM_SOCIAL_SECURITY_AND_PENSION_FUNDS(AccountCategoryGroup.OTHER_SHORT_TERM_RECEIVABLES),
    WITHHOLDING_TAX_CREDITS(AccountCategoryGroup.OTHER_SHORT_TERM_RECEIVABLES),
    OTHER_SHORT_TERM_RECEIVABLES(AccountCategoryGroup.OTHER_SHORT_TERM_RECEIVABLES),

    INVESTMENTS(AccountCategoryGroup.INVESTMENTS),

    MACHINERY_AND_EQUIPMENT(AccountCategoryGroup.MOVABLE_TANGIBLE_ASSETS),
    OFFICE_MACHINES_AND_IT_EQUIPMENT(AccountCategoryGroup.MOVABLE_TANGIBLE_ASSETS),
    TOOLS_AND_DEVICES(AccountCategoryGroup.MOVABLE_TANGIBLE_ASSETS),
    FURNITURE_AND_FIXTURES(AccountCategoryGroup.MOVABLE_TANGIBLE_ASSETS),
    VEHICLES(AccountCategoryGroup.MOVABLE_TANGIBLE_ASSETS),

    COMMERCIAL_PROPERTY(AccountCategoryGroup.IMMOVABLE_TANGIBLE_ASSETS),

    SECURITIES(AccountCategoryGroup.FINANCIAL_ASSETS),
    LOANS_TO_OTHERS(AccountCategoryGroup.FINANCIAL_ASSETS),
    MORTGAGES_TO_OTHERS(AccountCategoryGroup.FINANCIAL_ASSETS),

    PATENTS(AccountCategoryGroup.INTANGIBLE_ASSETS),
    KNOW_HOW(AccountCategoryGroup.INTANGIBLE_ASSETS),
    LICENSES(AccountCategoryGroup.INTANGIBLE_ASSETS),
    RIGHTS(AccountCategoryGroup.INTANGIBLE_ASSETS),
    DEVELOPMENTS(AccountCategoryGroup.INTANGIBLE_ASSETS),

    SHORT_TERM_BANK_LIABILITIES(AccountCategoryGroup.SHORT_TERM_INTEREST_BEARING_LIABILITIES),
    SHORT_TERM_LIABILITIES_FROM_FINANCE_LEASES(AccountCategoryGroup.SHORT_TERM_INTEREST_BEARING_LIABILITIES),
    OTHER_INTEREST_BEARING_LIABILITIES(AccountCategoryGroup.SHORT_TERM_INTEREST_BEARING_LIABILITIES),

    SHORT_TERM_PROVISIONS(AccountCategoryGroup.SHORT_TERM_PROVISIONS),

    WITHHOLDING_TAX(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),
    SOURCE_TAX(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),
    DIRECT_TAXES(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),
    OTHER_SHORT_TERM_LIABILITIES(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),
    DECLARED_DISTRIBUTIONS(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),
    SOCIAL_SECURITY_AND_PENSION_FUNDS(AccountCategoryGroup.OTHER_SHORT_TERM_LIABILITIES),

    MORTGAGES(AccountCategoryGroup.LONG_TERM_INTEREST_BEARING_LIABILITIES),
    LOANS(AccountCategoryGroup.LONG_TERM_INTEREST_BEARING_LIABILITIES),
    BOND_LOANS(AccountCategoryGroup.LONG_TERM_INTEREST_BEARING_LIABILITIES),
    LONG_TERM_LIABILITIES_FROM_FINANCE_LEASES(AccountCategoryGroup.LONG_TERM_INTEREST_BEARING_LIABILITIES),
    LONG_TERM_BANK_LIABILITIES(AccountCategoryGroup.LONG_TERM_INTEREST_BEARING_LIABILITIES),

    LONG_TERM_PROVISIONS(AccountCategoryGroup.LONG_TERM_PROVISIONS),

    OTHER_LONG_TERM_LIABILITIES(AccountCategoryGroup.OTHER_LONG_TERM_LIABILITIES),

    SHARE_NOMINAL_PARTICIPATION_OR_FOUNDATION_CAPITAL(AccountCategoryGroup.SHARE_SHAREHOLDERS_OR_FOUNDATION_CAPITAL),
    TREASURY_QUOTA_OR_PARTICIPATION_SHARES(AccountCategoryGroup.SHARE_SHAREHOLDERS_OR_FOUNDATION_CAPITAL),

    LEGAL_CAPITAL_RESERVE(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),
    PROFIT_OR_LOSS_CARRYFORWARD(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),
    ANNUAL_PROFIT_OR_LOSS(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),
    REVALUATIUON_RESERVE(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),
    LEGAL_PROFIT_RESERVE(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),
    VOLUNTARY_PROFIT_RESERVE(AccountCategoryGroup.RESERVES_NET_INCOME_NET_LOSS),

    PRODUCTION_REVENUE(AccountCategoryGroup.REVENUE),
    TRADING_REVENUE(AccountCategoryGroup.REVENUE),
    SERVICE_REVENUE(AccountCategoryGroup.REVENUE),
    OTHER_REVENUE(AccountCategoryGroup.REVENUE),
    OWN_WORK(AccountCategoryGroup.REVENUE),
    OWN_CONSUMPTION(AccountCategoryGroup.REVENUE),
    REVENUE_REDUCTIONS(AccountCategoryGroup.REVENUE),
    LOSSES_FROM_RECEIVABLES(AccountCategoryGroup.REVENUE),
    CHANGES_IN_INVENTORIES_OF_FINISHED_PRODUCTS(AccountCategoryGroup.REVENUE),
    CHANGES_IN_INVENTORIES_OF_UNFINISHED_PRODUCTS(AccountCategoryGroup.REVENUE),
    CHANGES_IN_INVENTORIES_OF_UNBILLED_SERVICES(AccountCategoryGroup.REVENUE),

    FINANCIAL_REVENUE(AccountCategoryGroup.FINANCIAL_RESULT_REVENUE),

    ANCILLARY_OPERATIONS_REVENUE(AccountCategoryGroup.OTHER_REVENUE),
    OPERATING_REAL_ESTATE_REVENUE(AccountCategoryGroup.OTHER_REVENUE),
    NON_OPERATING_REVENUE(AccountCategoryGroup.OTHER_REVENUE),
    EXTRAORDINARY_NON_RECURRING_OR_PRIOR_PERIOD_REVENUE(AccountCategoryGroup.OTHER_REVENUE),

    MATERIALS_FOR_PRODUCTION(AccountCategoryGroup.PRODUCTION_AND_SERVICES),
    MERCHANDISE_PRODUCTION(AccountCategoryGroup.PRODUCTION_AND_SERVICES),
    PURCHASED_SERVICES(AccountCategoryGroup.PRODUCTION_AND_SERVICES),
    ENERGY_FOR_PRODUCTION(AccountCategoryGroup.PRODUCTION_AND_SERVICES),
    EXPENSE_REDUCTIONS(AccountCategoryGroup.PRODUCTION_AND_SERVICES),

    WAGES(AccountCategoryGroup.PERSONNEL),
    SOCIAL_SECURITY_CONTRIBUTIONS(AccountCategoryGroup.PERSONNEL),
    OTHER_PERSONNEL_EXPENSES(AccountCategoryGroup.PERSONNEL),
    THIRD_PARTY_SERVICES(AccountCategoryGroup.PERSONNEL),

    MAINTENANCE_REPAIRS_REPLACEMENT_OF_MOBILE_TANGIBLE_ASSETS(AccountCategoryGroup.TRANSPORT_LEASING_AND_MAINTENANCE),
    LEASING_OF_MOBILE_TANGIBLE_ASSETS(AccountCategoryGroup.TRANSPORT_LEASING_AND_MAINTENANCE),
    VEHICLE_LEASING_AND_RENTAL(AccountCategoryGroup.TRANSPORT_LEASING_AND_MAINTENANCE),
    VEHICLE_AND_TRANSPORTATION_EXPENSES(AccountCategoryGroup.TRANSPORT_LEASING_AND_MAINTENANCE),

    PREMISES(AccountCategoryGroup.OPERATING_COSTS),
    IT_EXPENSES(AccountCategoryGroup.OPERATING_COSTS),
    ENERGY_AND_WASTE_DISPOSAL(AccountCategoryGroup.OPERATING_COSTS),
    ADVERTISING(AccountCategoryGroup.OPERATING_COSTS),
    ADMINISTRATION(AccountCategoryGroup.OPERATING_COSTS),
    PROPERTY_INSURANCE_TAXES_AND_PERMITS(AccountCategoryGroup.OPERATING_COSTS),
    DEPRECIATION(AccountCategoryGroup.OPERATING_COSTS),
    OTHER_OPERATING_EXPENSES(AccountCategoryGroup.OPERATING_COSTS),

    FINANCIAL_EXPENSE(AccountCategoryGroup.FINANCIAL_RESULT_EXPENSE),

    ANCILLARY_OPERATIONS_EXPENSE(AccountCategoryGroup.OTHER_EXPENSE),
    OPERATING_REAL_ESTATE_EXPENSE(AccountCategoryGroup.OTHER_EXPENSE),
    NON_OPERATING_EXPENSES(AccountCategoryGroup.OTHER_EXPENSE),
    EXTRAORDINARY_NON_RECURRING_OR_PRIOR_PERIOD_EXPENSE(AccountCategoryGroup.OTHER_EXPENSE),
    DIRECT_TAXES_EXPENSE(AccountCategoryGroup.OTHER_EXPENSE),
}